### ISSUE TITLE
一些工程问题

### ISSUE THREAD

**Issue by ATFmxyl** [Jawez/FileManager#1]
.qm文件不存在
解决办法
lrelease FileManager.pro

奇怪的字符问题
对应文件的编码改成UTF8-BOM

**Comment by edgebay** [comment]
.qm文件可以看下工程说明下的注意事项；
文件编码应该是Qt Creator里的默认编码格式，用其它IDE打开工程浏览编译的话有可能需要调整下文件的编码格式

**Comment by ATFmxyl** [comment]
> .qm文件可以看下工程说明下的注意事项； 文件编码应该是Qt Creator里的默认编码格式，用其它IDE打开工程浏览编译的话有可能需要调整下文件的编码格式

好的🆗
